buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath libs.google.protobuf.gradle
    }
}


apply plugin: 'com.android.library'
apply plugin: 'com.google.protobuf'
apply plugin: 'kotlin-android'

android {
    namespace = "com.svartifoss.snfell.common"


    defaultConfig {
        compileSdk 36
        minSdkVersion 21
        targetSdkVersion 30
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation project(path: ':wearutils')

    implementation libs.androidx.appCompat
    // Must have API to forward compiled protobuf files
    api libs.google.protobuf.liteRuntime

    testImplementation libs.junit4
    testImplementation libs.junit4.get()
}
repositories {
    mavenCentral()
}

kotlin {
    jvmToolchain(21)
}

protobuf {
    protoc {
        def dependency = libs.google.protobuf.protoc.get()
        artifact = "${dependency.module}:${dependency.versionConstraint}"
    }
    generateProtoTasks {
        all().each { task ->
            task.builtins {
                // Since protobuf 3.8 the Java Lite generator is built into protoc.
                // Keep generated code compatible with the javalite runtime brought
                // in by Firestore and avoid the obsolete protobuf-lite artifact.
                java {
                    option "lite"
                }
            }
        }
    }
}
